version: "3"  # optional since v1.27.0
services:
  mysql:
    image: mysql/mysql-server:8.0.26
    expose:
      - "3306"
    environment: 
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "NeilGwapo100%"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "ordering-system"
    volumes: 
      #- /var/lib/mysql:/var/lib/mysql #Docker Play Setup Only
      - MysqlBindVolume:/var/lib/mysql
    restart: always
  web:
    build: 
      context: . #Dockerfile
    #   #dockerfile: Dockerfile.local
    privileged: true
    # image: ngmedina14/ordering-system
    environment: 
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=NeilGwapo100%
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=ordering-system
    ports:
      - "8080:8080"
    volumes:
      - WebBindVolume:/go/src/github.com/OrderingSystem
    restart: unless-stopped
    depends_on: 
      - mysql
volumes:
  WebBindVolume:
    driver_opts:
        type: none
        device: ${PWD} #/home/neil/go/src/github.com/ngmedina14/OrderingSystem
        o: bind
  MysqlBindVolume:
    driver_opts:
        type: none
        device: ${PWD}/data #/home/neil/go/src/github.com/ngmedina14/OrderingSystem
        o: bind
    